server:
  port: 8080

spring:
  application:
    name: axon-tep-optimization
  # Jpa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.generate_statistics: true
      hibernate.session.events.log: false
      hibernate.jdbc.timezone: UTC
    database-platform: com.tep.config.PostgresqlBlobDialect
    mapping-resources: "DomainEventEntry.hbm.xml"

  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_demo_db
    username: wallet_demo_user
    password: password
    driver-class-name: org.postgresql.Driver

axon:
  serializer:
    events: jackson

app:
  event-generation:
    enabled: false
    count: 10000
  event-processing:
    processing-group-name:  demopublisher
    optimize-event-consumption: false
    cache-fetch-delay: 100ms
    parallel-processing-count: 4
    segmentation-count: 4
    batch-size: 100

logging:
  level:
    org.hibernate.stat.internal.StatisticsImpl: debug